services:
    php:
        image: wodby/php:latest
        volumes:
            - './:/var/www/html'
    nginx:
        image: nginx:latest
        ports:
            - 88:80
        links:
            - php
        volumes:
            - './:/var/www/html'
            - './docker/nginx:/etc/nginx/conf.d'
        depends_on:
            - php
            - mariadb
    mariadb:
        image: mariadb:latest
        environment:
            MYSQL_DATABASE: '${MYSQL_DATABASE}'
            MYSQL_USER: '${MYSQL_USER}'
            MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
            MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
        ports:
            - 3308:3306
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: mariadb
            PMA_USER: root
            PMA_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
        ports:
            - 1088:80
        depends_on:
            - mariadb